version: "3.1"

services:

  backend:
    build : . 
    ports:
    - 8000:3000
    volumes: 
    - .:/app 
    depends_on : 
     - db 

  db:
    image: mysql:5.7.22
    restart: always 
    environment: 
      MYSQL_DATABASE: ps-mean 
      MYSQL_USER : root 
      MYSQL_PASSWORD : '' 
      MYSQL_ROOT_PASSWORD : root 
    volumes: 
     - .dbdata:/var/lib/mysql
    ports: 
     - 33066:3306


